// <auto-generated />
using System;
using InfraMonitor.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfraMonitor.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InfraMonitor.Domain.Entities.Alert", b =>
                {
                    b.Property<int>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("MetricValue")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Triggered");

                    b.Property<double>("Threshold")
                        .HasColumnType("float");

                    b.HasKey("AlertId")
                        .HasName("PK__Alerts__EBB16A8D1D08808D");

                    b.HasIndex(new[] { "ServerId" }, "IX_Alerts_ServerId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("InfraMonitor.Domain.Entities.Disk", b =>
                {
                    b.Property<int>("DiskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiskId"));

                    b.Property<string>("DriveLetter")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<long>("FreeSpaceMb")
                        .HasColumnType("bigint")
                        .HasColumnName("FreeSpaceMB");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("TotalSpaceMb")
                        .HasColumnType("bigint")
                        .HasColumnName("TotalSpaceMB");

                    b.Property<double>("UsedPercentage")
                        .HasColumnType("float");

                    b.HasKey("DiskId")
                        .HasName("PK__Disks__1AC118DDEC88105B");

                    b.HasIndex(new[] { "ServerId", "Timestamp" }, "IX_Disks_ServerId_Timestamp");

                    b.ToTable("Disks");
                });

            modelBuilder.Entity("InfraMonitor.Domain.Entities.Metric", b =>
                {
                    b.Property<int>("MetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetricId"));

                    b.Property<double>("CpuUsage")
                        .HasColumnType("float");

                    b.Property<double>("DiskUsage")
                        .HasColumnType("float");

                    b.Property<double>("MemoryUsage")
                        .HasColumnType("float");

                    b.Property<double>("ResponseTime")
                        .HasColumnType("float");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MetricId")
                        .HasName("PK__Metrics__561056A5E8CCBF80");

                    b.HasIndex(new[] { "ServerId", "Timestamp" }, "IX_Metrics_ServerId_Timestamp");

                    b.ToTable("Metrics");
                });

            modelBuilder.Entity("InfraMonitor.Domain.Entities.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("ReportId")
                        .HasName("PK__Reports__D5BD480545356603");

                    b.HasIndex("ServerId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("InfraMonitor.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1AAFBAB3F9");

                    b.HasIndex(new[] { "Name" }, "UQ__Roles__737584F6779F8BB7")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("InfraMonitor.Domain.Entities.Server", b =>
                {
                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServerId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IPAddress");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Up");

                    b.HasKey("ServerId")
                        .HasName("PK__Servers__C56AC8E68A010455");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("InfraMonitor.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C5C9E587C");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D1053400C7BA05")
                        .IsUnique();

                    b.HasIndex(new[] { "UserName" }, "UQ__Users__C9F284569C71F078")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InfraMonitor.Domain.Entities.Alert", b =>
                {
                    b.HasOne("InfraMonitor.Domain.Entities.Server", "Server")
                        .WithMany("Alerts")
                        .HasForeignKey("ServerId")
                        .IsRequired()
                        .HasConstraintName("FK_Alerts_Servers");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("InfraMonitor.Domain.Entities.Disk", b =>
                {
                    b.HasOne("InfraMonitor.Domain.Entities.Server", "Server")
                        .WithMany("Disks")
                        .HasForeignKey("ServerId")
                        .IsRequired()
                        .HasConstraintName("FK_Disks_Servers");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("InfraMonitor.Domain.Entities.Metric", b =>
                {
                    b.HasOne("InfraMonitor.Domain.Entities.Server", "Server")
                        .WithMany("Metrics")
                        .HasForeignKey("ServerId")
                        .IsRequired()
                        .HasConstraintName("FK_Metrics_Servers");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("InfraMonitor.Domain.Entities.Report", b =>
                {
                    b.HasOne("InfraMonitor.Domain.Entities.Server", "Server")
                        .WithMany("Reports")
                        .HasForeignKey("ServerId")
                        .IsRequired()
                        .HasConstraintName("FK_Reports_Servers");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("InfraMonitor.Domain.Entities.User", b =>
                {
                    b.HasOne("InfraMonitor.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("InfraMonitor.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("InfraMonitor.Domain.Entities.Server", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Disks");

                    b.Navigation("Metrics");

                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
